### ISSUE TITLE
NatsError: stream not found

### ISSUE THREAD

**Issue by ItaiCovver** [BemiHQ/bemi#12]
I'm trying to run the docker container `public.ecr.aws/bemi/bemi-local:latest` locally and the Debezium seems to work and it is getting updates from the WAL and processing messages correctly but the Jetstream server seems to not be working and I do not see any updates in the `changes` table.

This is the error that I am getting
```
/worker/node_modules/.pnpm/nats@2.19.0/node_modules/nats/lib/jetstream/jsutil.js:194
            return new core_1.NatsError(description, core_1.ErrorCode.JetStream404NoMessages);
                   ^

NatsError: stream not found
    at checkJsErrorCode (/worker/node_modules/.pnpm/nats@2.19.0/node_modules/nats/lib/jetstream/jsutil.js:194:20)
    at ConsumerAPIImpl.parseJsResponse (/worker/node_modules/.pnpm/nats@2.19.0/node_modules/nats/lib/jetstream/jsbaseclient_api.js:95:55)
    at ConsumerAPIImpl.<anonymous> (/worker/node_modules/.pnpm/nats@2.19.0/node_modules/nats/lib/jetstream/jsbaseclient_api.js:74:25)
    at Generator.next (<anonymous>)
    at fulfilled (/worker/node_modules/.pnpm/nats@2.19.0/node_modules/nats/lib/jetstream/jsbaseclient_api.js:19:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: '404',
  chainedError: undefined,
  api_error: { code: 404, err_code: 10059, description: 'stream not found' }
}
```

**Comment by exAspArk** [comment]
Hi @ItaiCovver — would you be able to try again by running the following:

```sh
docker rmi -f public.ecr.aws/u4i4s8t6/bemi-local
docker run \
  -e DB_HOST=host.docker.internal \
  -e DB_PORT=5434 \
  -e DB_NAME=bemi_dev_source \
  -e DB_USER=postgres \
  -e DB_PASSWORD=postgres \
  public.ecr.aws/bemi/dev:latest 
```

This should pull the latest Docker image and output something like this:

> 2024-09-03 20:55:43,160 INFO  [io.deb.ser.nat.jet.NatsJetStreamChangeConsumer] (main) Creating stream with config: StreamConfiguration{name='DebeziumStream', description='The debezium stream, contains messages which are coming from debezium', subjects=[bemi, __debezium-heartbeat.*], retentionPolicy=limits, maxConsumers=-1, maxMsgs=-1, maxMsgsPerSubject=-1, maxBytes=-1, maxAge=PT0S, maxMsgSize=-1, storageType=memory, replicas=1, noAck=false, template='null', discardPolicy=old, duplicateWindow=PT0S, allowRollup=false, allowDirect=false, denyDelete=false, denyPurge=false, discardNewPerSubject=false, mirror=null, placement=null, sources=[]}

Once you see this log line, the `DebeziumStream` NATS stream should be created.

Please note that this Docker image is designed for local development environments only and is not recommended for use in production because of the reliability guarantees, configuration, etc.

**Comment by ItaiCovver** [comment]
Great this new image works and I see the `changes` table with data in it. For some reason the `before` column is empty but I don't really mind that for now. I contacted you guys through the website inquiring about the production docker images/setup.

I see you have already updated the docs with this new docker image! Thanks for the quick fix and reply!
