### ISSUE TITLE
Run Bemi on docker locally

### ISSUE THREAD

**Issue by anabel29** [BemiHQ/bemi#13]
Hi there, I'm trying to run bemi locally, i'm using docker command from tutorial:

```
  docker run \
  -e DB_HOST=host.docker.internal \
  -e DB_PORT=5434 \
  -e DB_NAME=bemi_dev_source \
  -e DB_USER=postgres \
  -e DB_PASSWORD=postgres \
  public.ecr.aws/bemi/dev:latest
```
Edit; I have my postgres db running on docker too
 
but I'm getting the same error as [Issue 12](https://github.com/BemiHQ/bemi/issues/12)

![image](https://github.com/user-attachments/assets/727e44be-ebd0-42c5-bcf9-c41cbb7b1bcd)

What i'm doing wrong? :(

**Comment by exAspArk** [comment]
Hi @anabel29 — the issue is related to the first error `ECONNREFUSED 127.0.0.1:5434`.

You'd likely need to modify these arguments to connect to PostgreSQL running on your local machine:

```
...
  -e DB_PORT=5434 \
  -e DB_NAME=bemi_dev_source \
  -e DB_USER=postgres \
  -e DB_PASSWORD=postgres \
  ...
```

Usually, PostgreSQL is running on port 5432 with `postgres` or some custom database name.

**Comment by anabel29** [comment]
Thanks for your answer, I made it to work finally :)
