### ISSUE TITLE
Stop the Bemi Mail Spam

### ISSUE THREAD

**Issue by fingers10** [BemiHQ/bemi#14]
I received cold spam mails pointing to this project sent from the address arjunlall.bemi@gmail.com. Are the team members of this project aware of this spam methods? And can you please stop this? Especially because this practice is illegal in some countries. I'll also file and report this to GitHub.

![image](https://github.com/user-attachments/assets/a46cd2d6-0c66-40a5-bf26-adf1243970be)

**Comment by arjunlol** [comment]
@fingers10 that wasn't my intention, and we definitely don’t want to send anything that feels like spam. This was recently also flagged by someone else. I'll close this out and not send those emails again.
